### ISSUE TITLE
train error 2

### ISSUE THREAD

**Issue by arnold-em** [tuananhphan97vn/HeterGraphLongSum#4]
Traceback (most recent call last):
  File "train.py", line 373, in <module>
    main()
  File "train.py", line 369, in main
    setup_training(model, train_loader, valid_loader, valid_dataset, hps)
  File "train.py", line 56, in setup_training
    run_training(model, train_loader, valid_loader, valset, hps, train_dir)
  File "train.py", line 101, in run_training
    outputs = model.forward(G_ws , G_wp , G_sp)  # [n_snodes, 2]
  File "/home/cht/cht/HeterGrapgLongSum/HeterGraphLongSum-main/HiGraph.py", line 111, in forward
    sent_feature = self.n_feature_proj(self.set_snfeature(graph_ws))    # [snode, n_feature_size]
  File "/home/cht/cht/HeterGrapgLongSum/HeterGraphLongSum-main/HiGraph.py", line 268, in set_snfeature
    cnn_feature = self._sent_cnn_feature(graph, snode_id)
  File "/home/cht/cht/HeterGrapgLongSum/HeterGraphLongSum-main/HiGraph.py", line 234, in _sent_cnn_feature
    cnn_feature = self.cnn_proj(ngram_feature + position_embedding)
RuntimeError: The size of tensor a (300) must match the size of tensor b (100) at non-singleton dimension 1
the tensor dimension dont match
may i use glove.42B.300d.txt?
please tell me 
thanks!!!
best
cht

**Comment by tuananhphan97vn** [comment]
Can you add the parameter: --word_emb_dim = 300 and rerun the program? It may be successful.

**Comment by tuananhphan97vn** [comment]
If you want run word_emb_dim=100 as default value , you should change         max_kernel_size = 7 in module/Encode.py -> max kernel size = 3. Good luck.

**Comment by arnold-em** [comment]
wow thanks it dose work！！！
thank you so much
i almost take a week！！！
you are appreciated！！！！



At 2022-11-22 23:12:31, "tuananhphan97vn" ***@***.***> wrote:

If you want run word_emb_dim=100 as default value , you should change max_kernel_size = 7 in module/Encode.py -> max kernel size = 3. Good luck.

**Comment by arnold-em** [comment]
hello sir
sorry to bother you again
when i run train.py
the dataload time so long （i use the same gpu Tesla V100 16g）
the loader time from the one to the next need nearly 38 mins
but train time is about 15s
2022-11-23 18:29:52,059 INFO : | end of iter 0 | time: 8.19s | train loss 0.3314 |
2022-11-23 18:43:33,030 INFO : | end of iter 100 | time: 5.98s | train loss 10.5012 |
2022-11-23 19:14:13,234 INFO : | end of iter 200 | time: 15.88s | train loss 10.0440 |
2022-11-23 19:51:34,120 INFO : | end of iter 300 | time: 15.85s | train loss 9.7475 |
2022-11-23 20:29:21,857 INFO : | end of iter 400 | time: 14.85s | train loss 9.5422 |
2022-11-23 21:05:25,303 INFO : | end of iter 500 | time: 15.89s | train loss 9.4115 |
2022-11-23 21:42:54,093 INFO : | end of iter 600 | time: 21.44s | train loss 9.2664 |
2022-11-23 22:20:35,378 INFO : | end of iter 700 | time: 18.20s | train loss 9.2983 |
2022-11-23 22:58:10,442 INFO : | end of iter 800 | time: 19.74s | train loss 9.2428 |
2022-11-23 23:34:37,864 INFO : | end of iter 900 | time: 15.15s | train loss 9.2534 |
2022-11-24 00:10:39,409 INFO : | end of iter 1000 | time: 15.31s | train loss 9.0840 |
2022-11-24 00:47:13,592 INFO : | end of iter 1100 | time: 18.46s | train loss 9.0827 |
2022-11-24 01:22:47,238 INFO : | end of iter 1200 | time: 15.76s | train loss 9.0300 |
2022-11-24 02:00:14,628 INFO : | end of iter 1300 | time: 15.26s | train loss 9.1111 |
2022-11-24 02:36:57,226 INFO : | end of iter 1400 | time: 16.48s | train loss 9.0457 |
2022-11-24 03:15:07,266 INFO : | end of iter 1500 | time: 15.17s | train loss 9.0220 |
2022-11-24 03:51:30,969 INFO : | end of iter 1600 | time: 15.33s | train loss 8.9799 |
2022-11-24 04:26:48,043 INFO : | end of iter 1700 | time: 16.31s | train loss 8.9735 |
2022-11-24 05:03:17,348 INFO : | end of iter 1800 | time: 14.59s | train loss 8.9098 |
2022-11-24 05:39:51,065 INFO : | end of iter 1900 | time: 16.48s | train loss 8.8784 |
2022-11-24 06:14:41,056 INFO : | end of iter 2000 | time: 15.22s | train loss 8.8681 |
2022-11-24 06:50:26,043 INFO : | end of iter 2100 | time: 14.66s | train loss 8.9206 |
2022-11-24 07:28:32,388 INFO : | end of iter 2200 | time: 14.90s | train loss 8.8088 |
2022-11-24 08:03:44,742 INFO : | end of iter 2300 | time: 14.98s | train loss 8.9108 |
2022-11-24 08:41:56,986 INFO : | end of iter 2400 | time: 14.91s | train loss 8.8643 |
2022-11-24 09:18:58,813 INFO : | end of iter 2500 | time: 14.86s | train loss 8.7507 |
2022-11-24 09:56:26,396 INFO : | end of iter 2600 | time: 15.03s | train loss 8.8055 |



At 2022-11-22 23:12:31, "tuananhphan97vn" ***@***.***> wrote:

If you want run word_emb_dim=100 as default value , you should change max_kernel_size = 7 in module/Encode.py -> max kernel size = 3. Good luck.

**Comment by arnold-em** [comment]
hello sir
sorry to bother you again
when i run train.py
the dataload time so long （i use the same gpu Tesla V100 16g）
the loader time from the one to the next need nearly 38 mins

but train time is about 15s
what should i do to short the time of dataloader？
thanks from a noob of text summarization... 
2022-11-23 18:29:52,059 INFO : | end of iter 0 | time: 8.19s | train loss 0.3314 |
2022-11-23 18:43:33,030 INFO : | end of iter 100 | time: 5.98s | train loss 10.5012 |
2022-11-23 19:14:13,234 INFO : | end of iter 200 | time: 15.88s | train loss 10.0440 |
2022-11-23 19:51:34,120 INFO : | end of iter 300 | time: 15.85s | train loss 9.7475 |
2022-11-23 20:29:21,857 INFO : | end of iter 400 | time: 14.85s | train loss 9.5422 |
2022-11-23 21:05:25,303 INFO : | end of iter 500 | time: 15.89s | train loss 9.4115 |
2022-11-23 21:42:54,093 INFO : | end of iter 600 | time: 21.44s | train loss 9.2664 |
2022-11-23 22:20:35,378 INFO : | end of iter 700 | time: 18.20s | train loss 9.2983 |
2022-11-23 22:58:10,442 INFO : | end of iter 800 | time: 19.74s | train loss 9.2428 |
2022-11-23 23:34:37,864 INFO : | end of iter 900 | time: 15.15s | train loss 9.2534 |
2022-11-24 00:10:39,409 INFO : | end of iter 1000 | time: 15.31s | train loss 9.0840 |
2022-11-24 00:47:13,592 INFO : | end of iter 1100 | time: 18.46s | train loss 9.0827 |
2022-11-24 01:22:47,238 INFO : | end of iter 1200 | time: 15.76s | train loss 9.0300 |
2022-11-24 02:00:14,628 INFO : | end of iter 1300 | time: 15.26s | train loss 9.1111 |
2022-11-24 02:36:57,226 INFO : | end of iter 1400 | time: 16.48s | train loss 9.0457 |
2022-11-24 03:15:07,266 INFO : | end of iter 1500 | time: 15.17s | train loss 9.0220 |
2022-11-24 03:51:30,969 INFO : | end of iter 1600 | time: 15.33s | train loss 8.9799 |
2022-11-24 04:26:48,043 INFO : | end of iter 1700 | time: 16.31s | train loss 8.9735 |
2022-11-24 05:03:17,348 INFO : | end of iter 1800 | time: 14.59s | train loss 8.9098 |
2022-11-24 05:39:51,065 INFO : | end of iter 1900 | time: 16.48s | train loss 8.8784 |
2022-11-24 06:14:41,056 INFO : | end of iter 2000 | time: 15.22s | train loss 8.8681 |
2022-11-24 06:50:26,043 INFO : | end of iter 2100 | time: 14.66s | train loss 8.9206 |
2022-11-24 07:28:32,388 INFO : | end of iter 2200 | time: 14.90s | train loss 8.8088 |
2022-11-24 08:03:44,742 INFO : | end of iter 2300 | time: 14.98s | train loss 8.9108 |
2022-11-24 08:41:56,986 INFO : | end of iter 2400 | time: 14.91s | train loss 8.8643 |
2022-11-24 09:18:58,813 INFO : | end of iter 2500 | time: 14.86s | train loss 8.7507 |
2022-11-24 09:56:26,396 INFO : | end of iter 2600 | time: 15.03s | train loss 8.8055 |



At 2022-11-22 23:12:31, "tuananhphan97vn" ***@***.***> wrote:

If you want run word_emb_dim=100 as default value , you should change max_kernel_size = 7 in module/Encode.py -> max kernel size = 3. Good luck.

**Comment by arnold-em** [comment]
i really sorry to bother you again
the dataloader time too long
did you met this situation before？



| |
常恒通
|
|
***@***.***
|

签名由 网易邮箱大师 定制

On 11/24/2022 10:25, Arnold_cht wrote:
hello sir
sorry to bother you again
when i run train.py
the dataload time so long （i use the same gpu Tesla V100 16g）
the loader time from the one to the next need nearly 38 mins

but train time is about 15s
what should i do to short the time of dataloader？
thanks from a noob of text summarization... 
2022-11-23 18:29:52,059 INFO : | end of iter 0 | time: 8.19s | train loss 0.3314 |
2022-11-23 18:43:33,030 INFO : | end of iter 100 | time: 5.98s | train loss 10.5012 |
2022-11-23 19:14:13,234 INFO : | end of iter 200 | time: 15.88s | train loss 10.0440 |
2022-11-23 19:51:34,120 INFO : | end of iter 300 | time: 15.85s | train loss 9.7475 |
2022-11-23 20:29:21,857 INFO : | end of iter 400 | time: 14.85s | train loss 9.5422 |
2022-11-23 21:05:25,303 INFO : | end of iter 500 | time: 15.89s | train loss 9.4115 |
2022-11-23 21:42:54,093 INFO : | end of iter 600 | time: 21.44s | train loss 9.2664 |
2022-11-23 22:20:35,378 INFO : | end of iter 700 | time: 18.20s | train loss 9.2983 |
2022-11-23 22:58:10,442 INFO : | end of iter 800 | time: 19.74s | train loss 9.2428 |
2022-11-23 23:34:37,864 INFO : | end of iter 900 | time: 15.15s | train loss 9.2534 |
2022-11-24 00:10:39,409 INFO : | end of iter 1000 | time: 15.31s | train loss 9.0840 |
2022-11-24 00:47:13,592 INFO : | end of iter 1100 | time: 18.46s | train loss 9.0827 |
2022-11-24 01:22:47,238 INFO : | end of iter 1200 | time: 15.76s | train loss 9.0300 |
2022-11-24 02:00:14,628 INFO : | end of iter 1300 | time: 15.26s | train loss 9.1111 |
2022-11-24 02:36:57,226 INFO : | end of iter 1400 | time: 16.48s | train loss 9.0457 |
2022-11-24 03:15:07,266 INFO : | end of iter 1500 | time: 15.17s | train loss 9.0220 |
2022-11-24 03:51:30,969 INFO : | end of iter 1600 | time: 15.33s | train loss 8.9799 |
2022-11-24 04:26:48,043 INFO : | end of iter 1700 | time: 16.31s | train loss 8.9735 |
2022-11-24 05:03:17,348 INFO : | end of iter 1800 | time: 14.59s | train loss 8.9098 |
2022-11-24 05:39:51,065 INFO : | end of iter 1900 | time: 16.48s | train loss 8.8784 |
2022-11-24 06:14:41,056 INFO : | end of iter 2000 | time: 15.22s | train loss 8.8681 |
2022-11-24 06:50:26,043 INFO : | end of iter 2100 | time: 14.66s | train loss 8.9206 |
2022-11-24 07:28:32,388 INFO : | end of iter 2200 | time: 14.90s | train loss 8.8088 |
2022-11-24 08:03:44,742 INFO : | end of iter 2300 | time: 14.98s | train loss 8.9108 |
2022-11-24 08:41:56,986 INFO : | end of iter 2400 | time: 14.91s | train loss 8.8643 |
2022-11-24 09:18:58,813 INFO : | end of iter 2500 | time: 14.86s | train loss 8.7507 |
2022-11-24 09:56:26,396 INFO : | end of iter 2600 | time: 15.03s | train loss 8.8055 |



At 2022-11-22 23:12:31, "tuananhphan97vn" ***@***.***> wrote:

If you want run word_emb_dim=100 as default value , you should change max_kernel_size = 7 in module/Encode.py -> max kernel size = 3. Good luck.

**Comment by tuananhphan97vn** [comment]
For training time is so long, the main reason is my graph is quite big with numerous of nodes. You should set num workers for dataloader higher. E.g: 32

**Comment by arnold-em** [comment]
thank u so much

**Comment by anushiya-thevapalan** [comment]
How did you manage to train on GPU? I was able to train a very small subset of data on CPU. But repeatedly getting CUDA error when I try with GPU (V100).

The error message isn't informative enough. I suspect that when moving the `G_ws` to the GPU it's causing issues.

```
Traceback (most recent call last):
  File "/content/drive/MyDrive/Academics/Masters/Research/dev/HeterGraphLongSumPro/train.py", line 379, in <module>
    main()
  File "/content/drive/MyDrive/Academics/Masters/Research/dev/HeterGraphLongSumPro/train.py", line 375, in main
    setup_training(model, train_loader, valid_loader, valid_dataset, hps)
  File "/content/drive/MyDrive/Academics/Masters/Research/dev/HeterGraphLongSumPro/train.py", line 55, in setup_training
    run_training(model, train_loader, valid_loader, valset, hps, train_dir)
  File "/content/drive/MyDrive/Academics/Masters/Research/dev/HeterGraphLongSumPro/train.py", line 99, in run_training
    G_ws.to(torch.device("cuda:0"))
  File "/usr/local/lib/python3.10/dist-packages/dgl/heterograph.py", line 5725, in to
    new_bnn = {
  File "/usr/local/lib/python3.10/dist-packages/dgl/heterograph.py", line 5726, in <dictcomp>
    k: F.copy_to(num, device, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dgl/backend/pytorch/tensor.py", line 143, in copy_to
    return input.cuda(**kwargs)
RuntimeError: CUDA error: unspecified launch failure
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Can you help me with any thoughts on this? 

In addition, can this be due to any version issues? What version of Python, Pytorch, CUDA and dgl did you use?
